# Включение и отключение проверок
disabled_rules:
 - explicit_enum_raw_value # Убираем требование явного указания raw-value для enum

# Настройка активных правил
opt_in_rules:
  - closure_end_indentation # Следим за правильным форматированием замыканий
  - closure_spacing # Обеспечиваем корректные пробелы в замыканиях
  - function_default_parameter_at_end # Параметры по умолчанию всегда в конце
  - empty_count  # Правило для замены `count == 0` на `isEmpty`
  - vertical_whitespace_between_cases # Требует пустую строку между case в перечислениях (enum)
  - operator_usage_whitespace # Проверяет пробелы вокруг операторов (например, `a + b` вместо `a+b`)
  - modifier_order # Требует определённый порядок модификаторов (например, public, final, override)
  - force_cast # Запрещаем использование force-cast, чтобы следовать принципам безопасности
  - force_try  # Избегаем force-try, так как это нарушает безопасность кода

# Настройка стиля именования
identifier_name:
  min_length: 3        # Минимальная длина идентификаторов
  max_length: 40       # Максимальная длина идентификаторов
  excluded:
    - id               # Исключение для часто используемых имен (например, id)

# Пробелы и отступы
line_length:
  warning: 100          # Рекомендуемая длина строки
  error: 120            # Предельная длина строки

trailing_whitespace:
  ignores_empty_lines: true # Игнорируем пустые строки
  ignores_comments: true    # Игнорируем комментарии

# Форматирование функций
function_body_length:
  warning: 40           # Предупреждение для длинных функций
  error: 60             # Ошибка, если функция слишком длинная

function_parameter_count:
  warning: 5            # Максимум 5 параметров
  error: 7              # Больше 7 параметров — ошибка
  
# Конвенции именования (CamelCase для переменных, PascalCase для типов)
type_name:
  min_length: 3
  max_length: 50
  validates_start_with_lowercase:
    severity: warning # PascalCase для типов

# Конфигурация правила empty_count
empty_count:
  severity: error         # Уровень: ошибка (выдаёт ошибку при нарушении)
  only_after_dot: false   # Проверять вызовы `count` даже без явного обращения через точку

# Строгий порядок модификаторов
modifier_order:
  severity: error

# Другие важные правила
legacy_hashing:
  severity: warning      # Используем современные функции для хеширования

type_body_length:
  warning: 300           # Предупреждение при длинных типах
  error: 400             # Ошибка, если тип слишком большой

vertical_whitespace_between_cases:
  severity: warning      # Пробелы между case в enum

# Исключаемые файлы
excluded:
 - AppDelegate.swift
 - SceneDelegate.swift

